# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AlegraCli < Formula
  desc "Command-line interface for the Alegra accounting API"
  homepage "https://github.com/jjuanrivvera/alegra-cli"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v0.4.3/alegra-cli_0.4.3_darwin_amd64.tar.gz"
      sha256 "f07ea4d2d8eaf14d94b7b0caa9c482552badcd5d729debc1a6cf451a68112ce6"

      define_method(:install) do
        bin.install "alegra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v0.4.3/alegra-cli_0.4.3_darwin_arm64.tar.gz"
      sha256 "0cb6f75b01026a0b1aa1287ce98165adb444e653db479e8eacb2e5122dab4e15"

      define_method(:install) do
        bin.install "alegra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v0.4.3/alegra-cli_0.4.3_linux_amd64.tar.gz"
      sha256 "57cba9115600f8eac833b3addc71626ed3f93aff0c31bc559ca54522dfd31537"
      define_method(:install) do
        bin.install "alegra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v0.4.3/alegra-cli_0.4.3_linux_arm64.tar.gz"
      sha256 "516afcab9619cd24af4f246ae5cf6dd404569b4d8700a5052a4b15c96806ddd8"
      define_method(:install) do
        bin.install "alegra"
      end
    end
  end

  test do
    system "#{bin}/alegra version"
  end
end
