# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AlegraCli < Formula
  desc "Command-line interface for the Alegra accounting API"
  homepage "https://github.com/jjuanrivvera/alegra-cli"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v0.4.2/alegra-cli_0.4.2_darwin_amd64.tar.gz"
      sha256 "47c3a036d59c50f50370f0e316fe52173eeffd71f3935a768e019d7d4b949712"

      define_method(:install) do
        bin.install "alegra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v0.4.2/alegra-cli_0.4.2_darwin_arm64.tar.gz"
      sha256 "1e0631b522d9bb5760a4e2bf6aadced78af0d13da5b0e2235cd12f16b993896b"

      define_method(:install) do
        bin.install "alegra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v0.4.2/alegra-cli_0.4.2_linux_amd64.tar.gz"
      sha256 "450876668e4ef4e813b1b682ad8bccc3636dcb8584ab32056017878f2194ba45"
      define_method(:install) do
        bin.install "alegra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v0.4.2/alegra-cli_0.4.2_linux_arm64.tar.gz"
      sha256 "ac284be1d3fe7c9c880a4057efad37882e20f091b0d161088394bc1020cc4fe4"
      define_method(:install) do
        bin.install "alegra"
      end
    end
  end

  test do
    system "#{bin}/alegra version"
  end
end
