# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AlegraCli < Formula
  desc "Command-line interface for the Alegra accounting API"
  homepage "https://github.com/jjuanrivvera/alegra-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v0.1.0/alegra-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "df69783ac934cbba018378a6015a77fafb832d61eaa1bb2927c31a4ebe8f5e75"

      define_method(:install) do
        bin.install "alegra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v0.1.0/alegra-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "41fcd350a0c3d96b62205789d211ba4b04066acce418a4d8cb412331b4953ee9"

      define_method(:install) do
        bin.install "alegra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v0.1.0/alegra-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "835ec005d135b85698c03b81a97a1c0ce9ce56d754a70e4332635b4dc16cdc8e"
      define_method(:install) do
        bin.install "alegra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v0.1.0/alegra-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "ba7319def526f6b8aa751163db15291e4a48202bfd7a162b7ebd74271ae40680"
      define_method(:install) do
        bin.install "alegra"
      end
    end
  end

  test do
    system "#{bin}/alegra version"
  end
end
