# This file was generated by GoReleaser. DO NOT EDIT.
cask "alegra-cli" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "1b411c84527319be8c3179595c5531f681982304bb4208a53b62b65e81eb15e6"
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v#{version}/alegra-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ddd54795eab2c2f8641a955fc834375d1f17fe8d8257d96ab5812a805de25e52"
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v#{version}/alegra-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a98df6de1b28029afe662bb1a1bed67b00a64285e26ff00daa13363643a9603e"
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v#{version}/alegra-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a55c79636630859bdc4d01dd17112d60489c1787a7e102285421431b744144ef"
      url "https://github.com/jjuanrivvera/alegra-cli/releases/download/v#{version}/alegra-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "alegra-cli"
  desc "Command-line interface for the Alegra accounting API"
  homepage "https://github.com/jjuanrivvera/alegra-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "alegra"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/alegra"]
  end

  # No zap stanza required

end
